serverUrl: http://localhost:3000
outDir: out
ide: IDEA
plugins:
  - https://plugins.jetbrains.com/plugin/10037-csv
  - https://plugins.jetbrains.com/plugin/10080-rainbow-brackets
  - https://plugins.jetbrains.com/plugin/10485-kubernetes
  - https://plugins.jetbrains.com/plugin/10550-add-to-gitignore
  - https://plugins.jetbrains.com/plugin/1065-checkstyle-idea
  - https://plugins.jetbrains.com/plugin/10650-json-parser
  - https://plugins.jetbrains.com/plugin/10949-jms-messenger
  - https://plugins.jetbrains.com/plugin/11058-extra-icons
  - https://plugins.jetbrains.com/plugin/12798-tabnine-ai-code-completion-js-java-python-ts-rust-go-php--more/
  - https://plugins.jetbrains.com/plugin/1347-scala
  - https://plugins.jetbrains.com/plugin/13691-selenium-ui-testing
  - https://plugins.jetbrains.com/plugin/14308-doc-aware-search-everywhere
  - https://plugins.jetbrains.com/plugin/14877-jump-to-line
  - https://plugins.jetbrains.com/plugin/15075-jpa-buddy
  - https://plugins.jetbrains.com/plugin/15285-direnv-integration
  - https://plugins.jetbrains.com/plugin/16289-cucumber-
  - https://plugins.jetbrains.com/plugin/164-ideavim
  - https://plugins.jetbrains.com/plugin/2162-string-manipulation
  - https://plugins.jetbrains.com/plugin/6954-kotlin
  - https://plugins.jetbrains.com/plugin/6981-ini
  - https://plugins.jetbrains.com/plugin/7017-plantuml-integration
  - https://plugins.jetbrains.com/plugin/7125-grep-console
  - https://plugins.jetbrains.com/plugin/7157-javadoc
  - https://plugins.jetbrains.com/plugin/7160-camelcase
  - https://plugins.jetbrains.com/plugin/7177-file-watchers
  - https://plugins.jetbrains.com/plugin/7179-maven-helper
  - https://plugins.jetbrains.com/plugin/7234-wrap-to-column
  - https://plugins.jetbrains.com/plugin/7248-multirun
  - https://plugins.jetbrains.com/plugin/7391-asciidoc
  - https://plugins.jetbrains.com/plugin/7425-wakatime
  - https://plugins.jetbrains.com/plugin/7495--ignore
  - https://plugins.jetbrains.com/plugin/7499-gittoolbox
  - https://plugins.jetbrains.com/plugin/7724-docker
  - https://plugins.jetbrains.com/plugin/7793-markdown
  - https://plugins.jetbrains.com/plugin/8527-google-java-format
  - https://plugins.jetbrains.com/plugin/8554-ide-features-trainer
  - https://plugins.jetbrains.com/plugin/9223-heap-allocations-viewer
  - https://plugins.jetbrains.com/plugin/9525--env-files-support
  - https://plugins.jetbrains.com/plugin/9746-ideolog
  - https://plugins.jetbrains.com/plugin/9792-key-promoter-x
  - https://plugins.jetbrains.com/plugin/9836-randomness
  - https://plugins.jetbrains.com/plugin/7981-azure-devops
  - https://plugins.jetbrains.com/plugin/7535-gauge
  - https://plugins.jetbrains.com/plugin/7973-sonarlint
  - https://plugins.jetbrains.com/plugin/11938-one-dark-theme
  - https://plugins.jetbrains.com/plugin/11971-proguard-unscramble
  - https://plugins.jetbrains.com/plugin/15267-proguard-retrace-unscrambler
